// "use client"
import '../styles/globals.scss'
import { Inter } from 'next/font/google'
import Navbar from './shared/Navbar'
import Sidebar from './shared/Sidebar'
import styles from '../styles/Layout.module.scss'
import { useState } from 'react'
import Provider from './components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

    // const [isNavOpen, setIsNavOpen] = useState(false);

    return (
        <html lang="en">
            <Provider>
                <body className={inter.className}>
                    <Navbar />
                    <div className={styles.mainContent}>
                        <div className={styles.main}>
                            {children}
                        </div>
                    </div>
                </body>
            </Provider>
        </html>
    )
}
